In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('adult.csv')
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              32561 non-null  int64
 1   workclass        32561 non-null  object
 2   fnlwgt           32561 non-null  int64
 3   education        32561 non-null  object
 4   educational-num  32561 non-null  int64
 5   marital-status   32561 non-null  object
 6   occupation       32561 non-null  object
 7   relationship     32561 non-null  object
 8   race             32561 non-null  object
 9   gender           32561 non-null  object
 10  capital-gain     32561 non-null  int64
 11  capital-loss     32561 non-null  int64
 12  hours-per-week   32561 non-null  int64
 13  native-country   32561 non-null  object
 14  income           32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [4]:
df = df.drop(['fnlwgt','educational-num'],axis=1)
df_columns = df.columns

In [5]:
for c in df_columns:
    df = df.replace('?',np.NaN)
df = df.apply(lambda x: x.fillna(x.value_counts().index[0]))

In [6]:
df.replace(['Divorced', 'Married-AF-spouse',
			'Married-civ-spouse', 'Married-spouse-absent',
			'Never-married', 'Separated', 'Widowed'],
		['divorced', 'married', 'married', 'married',
			'not married', 'not married', 'not married'], inplace=True)

In [7]:
category_col = ['workclass', 'race', 'education', 'marital-status', 'occupation',
				'relationship', 'gender', 'native-country', 'income']
from sklearn.preprocessing  import LabelEncoder
from  sklearn.tree import DecisionTreeClassifier

In [8]:
df.head()

,age,workclass,education,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [14]:
from sklearn.pipeline import  Pipeline,make_pipeline
from sklearn.compose import ColumnTransformer
prepro = Pipeline(steps=[('label_encoder',LabelEncoder())])
pipe = ColumnTransformer(transformers=[('column_transfer',prepro,['workclass', 'race', 'education', 'marital-status', 'occupation',
				'relationship', 'gender', 'native-country', 'income'])])
model = make_pipeline(pipe,DecisionTreeClassifier())

In [15]:
model

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('column_transfer',
                                                  Pipeline(steps=[('label_encoder',
                                                                   LabelEncoder())]),
                                                  ['workclass', 'race',
                                                   'education',
                                                   'marital-status',
                                                   'occupation', 'relationship',
                                                   'gender', 'native-country',
                                                   'income'])])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X = df.values[:,0:12]
Y = df.values[:,12]

In [17]:
X_train, X_test, y_train,  y_test = train_test_split(X,Y,test_size=0.3,random_state=100)
model.fit(X_train,y_train)
# y_pred_gini = pipe.predict(X_test)
# print('Decision Tree using Gini index\nAccuracy is',accuracy_score(y_test,y_pred_gini)*100)

ValueError: Specifying the columns using strings is only supported for pandas DataFrames

In [13]:
df

,age,workclass,education,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [14]:
import pickle
pickle.dump(dt_clf_gini, open('model.pkl', 'wb'))